config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'uploads#new'
  resources :uploads
  resources :downloads

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :owner, class_name: "User", foreign_key: :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :uploads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  def new
  end

  def create
    #upload = Upload.find_by(name: params[:name])
    obj = S3_BUCKET.objects[params[:name]]
    File.open(params[:name].split('/')[1], 'wb') do |file|
      obj.read do |chunk|
        file.write(chunk)
      end
    end
    send_file(params[:name].split('/')[1],
      :type => 'application/pdf/docx/html/htm/doc/jpg',
      :disposition => 'attachment') 
  end

  def index
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :index]
  before_action :set_upload
  def new
    if current_user.folder.nil?
      current_user.folder = current_user.email
      current_user.save
    end
    @uploads = S3_BUCKET.objects.with_prefix(current_user.folder + '/')
  end

  def create
    # Make an object in your bucket for your upload
    if not params[:file]
        flash.now[:alert] = 'Please select file for upload first'
        @uploads = S3_BUCKET.objects.with_prefix(current_user.folder + '/')
        render :new
        return
    end
    loc = current_user.folder + '/' + params[:file].original_filename
    obj = S3_BUCKET.objects[loc]

    # Upload the file
    obj.write(
      file: params[:file],
      acl: :public_read
    )

    # Create an object for the upload
    @upload = Upload.new(
            url: obj.public_url,
            name: obj.key,
            user_id: current_user,
            path: loc)
    # Save the upload
    if @upload.save
      flash.now[:notice] = 'File is uploaded successfully'
    else
      flash.now[:notice] = 'There was an error'
    end
    @uploads = S3_BUCKET.objects.with_prefix(current_user.folder + '/')
    render :new
  end

  def index
    if current_user.folder.nil?
      current_user.folder = current_user.email
      current_user.save
    end
    @uploads = S3_BUCKET.objects.with_prefix(current_user.folder + '/')
  end

  private
    def set_upload
      @user = User.find(current_user)
      @upload = @user.uploads
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = { notice: :success, alert: :danger }

    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end
end

app/helpers/downloads_helper.rb
module DownloadsHelper
  def download_file(path, filename)
    obj = S3_BUCKET.objects[path]
    File.open(filename, 'wb') do |file|
      obj.read do |chunk|
        file.write(chunk) 
      end
    end
  end

end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Personal File Manager</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li> <%= link_to("Sign On", new_user_registration_path) %> </li>
          <li> <%= link_to("Log in", new_user_session_path) %> </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to("Log Out", destroy_user_session_path, method: :delete) %> </li>
            </ul>
          </li>
        <% end %> 
      </ul>
    </div>
  </div>
</nav>

app/views/downloads/create.html.erb
<h1>Downloads#create</h1>
<p>Find me in app/views/downloads/create.html.erb</p>

app/views/downloads/index.html.erb
<h1>Downloads#index</h1>
<p>Find me in app/views/downloads/index.html.erb</p>

app/views/downloads/new.html.erb
<h1>Downloads#new</h1>
<p>Find me in app/views/downloads/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Personalfilemanager" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
    </div>    

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

  </body>
</html>

app/views/uploads/create.html.erb
<h1>Uploads#create</h1>
<p>Find me in app/views/uploads/create.html.erb</p>

app/views/uploads/index.html.erb
<h1>Image List</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>File Name</th>
        </tr>
    </thead>
    <% @uploads.each do |upload| %>
        <tr>
            <td width="400px"><%= upload.key.split('/')[1] %></td>
            <td><%= button_to "Download", downloads_path(:name => upload.key), method: :post %></td>
        </tr>
    <% end %>
</table> 

app/views/uploads/new.html.erb
<h1>Upload Files</h1>
<%= form_tag uploads_path, enctype: 'multipart/form-data', :class => 'form-inline' do %>
  <%= file_field_tag :file, :class =>"input-append" %>
  <br>
  <%= submit_tag 'Upload file', :class => 'btn btn-primary' %>
<% end %>

<h1>Current Files</h1>
<table class="table table-striped">
  <% if @uploads %>  
  <thead>
    <tr>
      <th>File Name</th>
    </tr>
  </thead>
  <% @uploads.each do |upload| %>
    <tr>
      <td width="400px"><%= upload.key.split('/')[1] %></td>
      <td><%= button_to "Download", downloads_path(:name => upload.key), method: :post, :class => 'btn btn-info' %></td>
    </tr>
  <% end %>
  <% else %>
  No file.
  <% end %>
</table> 